version: '2.1'
services:

  git:
    image: gogs/gogs
    ports:
     - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-3000}:${HTTP_PORT:-3000}"
     - "${SSH_BIND:-0.0.0.0}:${SSH_PORT:-10022}:${SSH_PORT:-10022}"
    volumes:
     - ./data/git/:/data:rw
    links:
     - git_db:mysqli

  git_db:
    image: mysql:5.6
    environment:
     - MYSQL_ROOT_PASSWORD=${DBROOT}
     - MYSQL_DATABASE=${DBNAME}
     - MYSQL_USER=${DBUSER}
     - MYSQL_PASSWORD=${DBPASS}
    volumes:
     - git-db-vol-1:/var/lib/mysql:rw

volumes:
  git-db-vol-1:
