version: '2.1'
services:

  git:
    image: gogs/gogs
    ports:
     - "3000:3000"
     - "10022:10022"
    volumes:
     - ./data/git/:/data:rw
    links:
     - git_db:mysqli

  git_db:
    image: mysql:5.6
    environment:
     - MYSQL_ROOT_PASSWORD=${DBROOT}
     - MYSQL_DATABASE=${DBNAME}
     - MYSQL_USER=${DBUSER}
     - MYSQL_PASSWORD=${DBPASS}
    volumes:
     - git-db-vol-1:/var/lib/mysql:rw

volumes:
  git-db-vol-1:
